const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,DB=path.join(__dirname,"data.json");
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
function load(){if(!fs.existsSync(DB)){fs.writeFileSync(DB,JSON.stringify({businesses:[{id:"demo",name:"Adwoa Fashion Hub",slug:"adwoa-fashion",whatsapp:"233241234567",location:"Kumasi, Ghana",hours:"Mon–Sat, 8 AM–7 PM",description:"Fashion, accessories and everyday essentials."}],products:[{id:"p1",businessId:"demo",name:"Classic Sneakers",price:180,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80",description:"Comfortable everyday sneakers."},{id:"p2",businessId:"demo",name:"Premium Handbag",price:220,image:"https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80",description:"Elegant handbag."},{id:"p3",businessId:"demo",name:"Perfume Spray",price:120,image:"https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=700&q=80",description:"Fresh everyday fragrance."}]},null,2))}return JSON.parse(fs.readFileSync(DB,"utf8"))}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}function id(){return crypto.randomBytes(8).toString("hex")}function slugify(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50)}
app.get("/api/business/:slug",(q,r)=>{const d=load(),b=d.businesses.find(x=>x.slug===q.params.slug);if(!b)return r.status(404).json({error:"Shop not found"});r.json({business:b,products:d.products.filter(x=>x.businessId===b.id)})});
app.post("/api/businesses",(q,r)=>{const {name,whatsapp,location,hours,description}=q.body||{};if(!name||!whatsapp)return r.status(400).json({error:"Business name and WhatsApp number are required"});const d=load();let s=slugify(name)||"shop",base=s,n=2;while(d.businesses.some(x=>x.slug===s))s=base+"-"+n++;const b={id:id(),name,slug:s,whatsapp:String(whatsapp).replace(/\D/g,""),location:location||"Ghana",hours:hours||"Contact seller",description:description||"",createdAt:new Date().toISOString()};d.businesses.push(b);save(d);r.json({ok:true,business:b,shopUrl:"/shop/"+b.slug})});
app.post("/api/products",(q,r)=>{const {businessId,name,price,image,description}=q.body||{},d=load();if(!businessId||!d.businesses.some(x=>x.id===businessId))return r.status(400).json({error:"Valid business required"});if(!name||!price)return r.status(400).json({error:"Product name and price are required"});const p={id:id(),businessId,name,price:Number(price),image:image||"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80",description:description||""};d.products.push(p);save(d);r.json({ok:true,product:p})});
app.delete("/api/products/:id",(q,r)=>{const d=load(),n=d.products.length;d.products=d.products.filter(x=>x.id!==q.params.id);if(n===d.products.length)return r.status(404).json({error:"Product not found"});save(d);r.json({ok:true})});
app.get("/shop/:slug",(q,r)=>r.sendFile(path.join(__dirname,"public","shop.html")));app.get("/seller",(q,r)=>r.sendFile(path.join(__dirname,"public","seller.html")));app.get("*splat",(q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("ShopLink Ghana V2 running on port "+PORT));